### ISSUE TITLE
edit temperature sensor 12-HD Max 	

### ISSUE THREAD

**Issue by javifly** [alex3025/ilo-fans-controller#14]
one of my temperature sensors has broken down and is showing very high values, it is the "12-HD Max" because of this the server is shutting down due to thermal protection. There would be a way to disable this sensor or raise the critical temperature value about 10 degrees ...? thanks

**Comment by alex3025** [comment]
This tool doesn't make use of temperature sensors.

Instead, check out the available commands in the [iLO patch](https://github.com/kendallgoto/ilo4_unlock), I think there should be a way to fix your issue.
