### ISSUE TITLE
Feature request: Execute commands from the web

### ISSUE THREAD

**Issue by javifly** [alex3025/ilo-fans-controller#15]
Some of us need to execute commands manually, is it possible to implement a window where we can write them and execute them via ssh in the ilo?

I tell you my problem, I have a faulty temperature sensor and I need to modify its values:

https://github.com/kendallgoto/ilo4_unlock/issues/26

It would be very convenient to do the above because only one ssh user can connect, so if I connect to put my sensor command then I can not regulate the fans from the web.

feature request 2:
If you restart the ilo, the configured values are lost. It would be possible to create another window where you can configure a crond and some values to be executed. In such a way that if we know what values we want to have always fixed in the Ilo we can set them to run every 60 minutes.  So if the Ilo is reset by a jz cut, it will configure itself again. 

Thanks

**Comment by alex3025** [comment]
This seems a bit out of the scope of the project, my tool was made only to set fans speeds, not as a GUI for the iLO CLI.

As you mentioned cron, why you just don't make a crontab entry `@reboot` applying your configuration values through ssh?

**Comment by javifly** [comment]
I don't have much knowledge of linux, I wouldn't know how to do it. I was asking because if you think it's a good idea and it doesn't take you long to implement it, I was waiting for it. I wouldn't know myself.
