### ISSUE TITLE
new preset name check is broken

### ISSUE THREAD

**Issue by Soltinator** [alex3025/ilo-fans-controller#19]
i tried both chromium and librewolf (based on firefox)
and when i go to make a new preset with any name, it says:

"A preset with the same speeds already exists (Silent Mode)."

im using debian and portainer
here is my compose file:

```Dockerfile
services:
  ilo-fans-controller:   
    image: ghcr.io/alex3025/ilo-fans-controller:latest
    container_name: ilo-fan-controller
    ports:
      - "8092:80"
    environment:
      ILO_HOST: '192.168.1.2'  # Ex. 192.168.1.69
      ILO_USERNAME: 'fan'  # Ex. Administrator
      ILO_PASSWORD: '****'  # Ex. AdministratorPassword1234
```

i had a issue with docker hub making the image from scratch like that so i used the latest tag.
if you kindly look into it id appreciate it.

and yes. i do have a dedicated fan account in my ilo with least permissions.

**Comment by alex3025** [comment]
@Soltinator

When you click on the create preset button, a new preset is made from the current speeds configuration (eg. Fan 1 at 20%, Fan 2 at 17%, Fan 3 at 35%, etc...).

The default "Silent Mode" preset is configured to set all the fan speeds to 15%, so if you're creating a preset that also have all fan speeds to the same value, you will get that error (the name doesn't matter).

If you were creating a preset with different speeds, and you got that error, try deleting all the default presets (using left-click) and create a new one with the speeds that you want.

If it's still not working, I'll provide further assistance :)
