### ISSUE TITLE
Undefined array key "Fans" in Index.php

### ISSUE THREAD

**Issue by tombull89** [alex3025/ilo-fans-controller#3]
Hi there, just span up a new machine to test this with and have ran into some issues.

Patched BIOS Version: 2.77
Hardware: ProLiant ML150 Gen9
OS: Ubuntu (Desktop) 22.04.2 LTS

Ran throught the install, updated and then installed the components. Loaded the webpage and get no fans. Tried with FQDN of iLO and IP, both have same result.

Looked through apache logs and found the below - variouslogs of the same.

```
[Wed May 03 21:51:28.825633 2023] [php:warn] [pid 667] [client 192.168.1.221:57232] PHP Warning:  Undefined array key "Fans" in /var/www/html/ilo-fans-controller/index.php on line 54
[Wed May 03 21:51:28.825686 2023] [php:warn] [pid 667] [client 192.168.1.221:57232] PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/html/ilo-fans-controller/index.php on line 54
```
Probably missing something basic, but linux skills are limited.

![image](https://user-images.githubusercontent.com/38692205/236049394-e2274741-4a35-4908-be86-5a294d99993a.png)

**Comment by alex3025** [comment]
Hello, can you run this command on the machine where you installed this tool and report the output?
```sh
curl https://<ilo-address>/redfish/v1/chassis/1/Thermal -u <ilo-username>:<ilo-password> -skL | json_pp | head
```

**Comment by tombull89** [comment]
`curl https://IPOFILO/redfish/v1/chassis/1/Thermal -u USERNAME:PASSWORD! -skL | json_pp | head`
gives me a result of...
```
{
   "@odata.context" : "/redfish/v1/$metadata#Chassis/Members/1/Thermal$entity",
   "@odata.id" : "/redfish/v1/Chassis/1/Thermal/",
   "@odata.type" : "#Thermal.1.2.0.Thermal",
   "Fans" : [
      {
         "CurrentReading" : 27,
         "FanName" : "Fan 1",
         "Oem" : {
            "Hp" : {
```

**Comment by tombull89** [comment]
I get a single 0.

![image](https://user-images.githubusercontent.com/38692205/236276476-65f4ccbe-a18e-4120-bf5a-3ad84566cfef.png)

**Comment by alex3025** [comment]
Ok so, please add the following code **between** lines [`52-53`](https://github.com/alex3025/ilo-fans-controller/blob/4b43a43e38206ddbd13c1b5696171e673f345375/ilo-fans-controller.php#L52-L53) and report the output (that should™ also appear on the top side of the UI).

```php
print_r(substr($raw_ilo_data, -150) . '<br><br>'); var_dump(json_decode($raw_ilo_data, true)['Fans'][0]);
```

**Comment by tombull89** [comment]
Added the code and now get:
```
0ExtendedInfo":[{"MessageID":"Base.0.10.NoValidSession"}],"code":"iLO.0.10.ExtendedInfo","message":"See @Message.ExtendedInfo for more information."}}

NULL 
```

**Comment by tombull89** [comment]
Oh god damn it, the "NoValidSession" above gave it away - the password was wrong and missing a character off the end.

That's embarassing, especially as I copy/pasted the password from the config page to the iLO WEB GUI to test and confirm.

**Comment by alex3025** [comment]
So it is now working properly?

**Comment by tombull89** [comment]
It is, yes. Thank you for your support.

**Comment by alex3025** [comment]
Perfect! I'll mark this issue as resolved 😄 

Probably a better front-end error handling will be a good feature for the next updates.
