### ISSUE TITLE
Set Speed button just spins without action

### ISSUE THREAD

**Issue by nkfs** [alex3025/ilo-fans-controller#5]
I have the tool installed using apache2 and php 8.1.  The webpage loads, and I can see 6 fans present.  When I adjust any of the settings and hit "Set Speed", it just spins, and never does anything.  When looking at the iLO4 UI, it doesn't appear that it has made any changes.  I can see the fan controller user logged in, and I am able to utilize the fan control directly via ssh.  I am running 2.77 patched iLO.   Please let me know if there is additional ways to debug / troubleshoot with logs.

Thanks

**Comment by jpmeijers** [comment]
I had this same issue, until I realised I was missing the php-ssh2 extension. Please make sure you installed the extension by executing `php8.1-ssh2`, or something similar for your php version.
