### ISSUE TITLE
Feature request: Reset all changes

### ISSUE THREAD

**Issue by jpmeijers** [alex3025/ilo-fans-controller#8]
Sometimes one would want to give control back to iLO's control system. For example when you are not at home and it's a very hot day, and server life is more important than noise.

I think the only way to do this is by resetting iLO. One can do that via the web interface:
Information -> Diagnostics -> Reset iLO -> Reset

![image](https://github.com/alex3025/ilo-fans-controller/assets/948278/18df433c-89f9-454a-a3b1-2ff4e1d92e34)

Maybe one can reset the iLO controller via SSH too, but via the web interface might be quicker.

**Comment by alex3025** [comment]
Unfortunately, I never thought about this feature and I can't come up on how I could add it without messing up with the UI/UX.
